import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main className="w-full mx-auto px-4 md:px-8 bg-white">
          {/* Advertisement Banner */}
          <div className="bg-gray-900  text-center py-1 mb-4">
            <h2 className="font-bold text-sm sm:text-base">Special Offer: Get 20% off on all products!</h2>
          </div>

          {/* Main Content */}
          {children}
        </main>
      </body>
    </html>
  );
}
